apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pezzo-secret
  namespace: pezzo
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: pezzo-secret
  data:
  - secretKey: SENDGRID_API_KEY
    remoteRef:
      key: kv/prod/pezzo
      property: SENDGRID_API_KEY