# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: zookeeper-data
#   namespace: pezzo
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: kafka-data
#   namespace: pezzo
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: zookeeper
#   namespace: pezzo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: zookeeper
#   template:
#     metadata:
#       labels:
#         app: zookeeper
#     spec:
#       containers:
#       - name: zookeeper
#         image: confluentinc/cp-zookeeper:7.3.2
#         ports:
#         - containerPort: 2181
#         env:
#         - name: ZOOKEEPER_CLIENT_PORT
#           value: "2181"
#         - name: ZOOKEEPER_TICK_TIME
#           value: "2000"
#         volumeMounts:
#         - name: zookeeper-data
#           mountPath: /var/lib/zookeeper/data
#       volumes:
#       - name: zookeeper-data
#         persistentVolumeClaim:
#           claimName: zookeeper-data
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: zookeeper
#   namespace: pezzo
# spec:
#   selector:
#     app: zookeeper
#   ports:
#   - port: 2181
#     targetPort: 2181
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kafka
#   namespace: pezzo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka
#   template:
#     metadata:
#       labels:
#         app: kafka
#     spec:
#       containers:
#       - name: kafka
#         image: confluentinc/cp-kafka:7.3.2
#         ports:
#         - containerPort: 9092
#         - containerPort: 9093
#         env:
#         - name: KAFKA_BROKER_ID
#           value: "1"
#         - name: KAFKA_ZOOKEEPER_CONNECT
#           value: "zookeeper:2181"
#         - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#           value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
#         - name: KAFKA_ADVERTISED_LISTENERS
#           value: "PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:9093"
#         - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#           value: "1"
#         - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
#           value: "1"
#         - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
#           value: "1"
#         - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
#           value: "0"
#         volumeMounts:
#         - name: kafka-data
#           mountPath: /var/lib/kafka/data
#       volumes:
#       - name: kafka-data
#         persistentVolumeClaim:
#           claimName: kafka-data
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka
#   namespace: pezzo
# spec:
#   selector:
#     app: kafka
#   ports:
#   - name: external
#     port: 9092
#     targetPort: 9092
#   - name: internal
#     port: 9093
#     targetPort: 9093 