apiVersion: apps/v1
kind: Deployment
metadata:
  name: pezzo-console
  namespace: pezzo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pezzo-console
  template:
    metadata:
      labels:
        app: pezzo-console
    spec:
      imagePullSecrets:
        - name: acr
      containers:
      - name: pezzo-console
        image: sentencelabs.azurecr.io/pezzo-console:latest
        # image: ghcr.io/pezzolabs/pezzo/console:latest
        # Alternatively, you can use the build context from the original docker-compose
        # You would need to build and push this image to a registry first
        ports:
        - containerPort: 8080
        env:
        - name: SUPERTOKENS_CONNECTION_URI
          valueFrom:
            configMapKeyRef:
              name: pezzo-config
              key: SUPERTOKENS_CONNECTION_URI
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: pezzo-config
              key: REDIS_URL
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: pezzo-config
              key: DATABASE_URL
        - name: CLICKHOUSE_HOST
          value: "clickhouse"
        - name: CLICKHOUSE_PORT
          value: "8123"
        - name: CLICKHOUSE_USER
          value: "default"
        - name: CLICKHOUSE_PASSWORD
          value: "default"
        - name: NX_BASE_API_URL
          value: "https://api.pezzo.sentencelabs.ai"
        - name: NX_SUPERTOKENS_API_DOMAIN
          value: "https://api.pezzo.sentencelabs.ai"
        - name: NX_SUPERTOKENS_WEBSITE_DOMAIN
          value: "https://pezzo.sentencelabs.ai"
---
apiVersion: v1
kind: Service
metadata:
  name: pezzo-console
  namespace: pezzo
spec:
  selector:
    app: pezzo-console
  ports:
  - port: 8080
    targetPort: 8080 