apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: pezzo
spec:
  provider:
    vault:
      server: https://secrets.sentencelabs.ai
      path: kv
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: v2
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        kubernetes:
          mountPath: kubernetes
          role: vault
          # Optional service account reference
          serviceAccountRef:
            name: vault


---


apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: pezzo
  labels:
    name: vault