apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: pezzo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
  namespace: pezzo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-logs
  namespace: pezzo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 